const STEP_CHANGE = "STEP_CHANGE";
const STEP_COMPLETED = "STEP_COMPLETED";
const CHECKOUT_COMPLETED = "CHECKOUT_COMPLETED";
const CHECKOUT_PROCESSING = "CHECKOUT_PROCESSING";
const CHECKOUT_PROCESSED = "CHECKOUT_PROCESSED";
const FETCH_CHECKOUT = "FETCH_CHECKOUT";

export default {
  STEP_CHANGE,
  STEP_COMPLETED,
  CHECKOUT_COMPLETED,
  CHECKOUT_PROCESSING,
  CHECKOUT_PROCESSED,
  FETCH_CHECKOUT
};
