const FETCH_CART = "FETCH_CART";
const DELETE_CART = "DELETE_CART";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const UPDATE_QUANTITY = "UPDATE_QUANTITY";

export default {
  FETCH_CART,
  DELETE_CART,
  REMOVE_PRODUCT,
  UPDATE_QUANTITY
};
